name: maggrav
channels:
  - conda-forge
  - pytorch
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - bzip2=1.0.8=hda65f42_9
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cuda-cudart=12.6.77=h5888daf_0
  - cuda-cudart_linux-64=12.6.77=h3f2d84a_0
  - cuda-nvrtc=12.6.85=hbd13f7d_0
  - cuda-version=12.6=h7480c83_3
  - faiss-gpu=1.13.2=py3.12_h1b31e9c_0_cuda12.6
  - icu=78.2=h33c6efd_0
  - ld_impl_linux-64=2.45.1=default_hbd61a6d_101
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libcblas=3.11.0=5_h0358290_openblas
  - libcublas=12.6.4.1=h5888daf_1
  - libexpat=2.7.4=hecca717_0
  - libfaiss=1.13.2=h1b31e9c_0_cuda12.6
  - libffi=3.5.2=h3435931_0
  - libgcc=15.2.0=he0feb66_18
  - libgcc-ng=15.2.0=h69a702a_18
  - libgfortran=15.2.0=h69a702a_18
  - libgfortran5=15.2.0=h68bc16d_18
  - libgomp=15.2.0=he0feb66_18
  - libhwloc=2.12.2=default_hafda6a7_1000
  - libiconv=1.18=h3b78370_2
  - liblapack=3.11.0=5_h47877c9_openblas
  - liblzma=5.8.2=hb03c661_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libsqlite=3.51.2=hf4e2dac_0
  - libstdcxx=15.2.0=h934c35e_18
  - libuuid=2.41.3=h5347b49_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.15.1=he237659_1
  - libxml2-16=2.15.1=hca6bf5a_1
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=21.1.8=h4922eb0_0
  - mkl=2024.2.2=ha770c72_17
  - ncurses=6.5=h2d0b736_3
  - numpy=2.4.2=py312h33ff503_1
  - openssl=3.6.1=h35e630c_1
  - packaging=26.0=pyhcf101f3_0
  - pip=26.0.1=pyh8b19718_0
  - python=3.12.12=hd63d673_2_cpython
  - python_abi=3.12=8_cp312
  - readline=8.3=h853b02a_0
  - setuptools=82.0.0=pyh332efcf_0
  - tbb=2021.13.0=hb700be7_5
  - tk=8.6.13=noxft_h366c992_103
  - tzdata=2025c=hc9c84f9_1
  - wheel=0.46.3=pyhd8ed1ab_0
  - zstd=1.5.7=hb78ec9c_6
  - pip:
    - GitPython==3.1.46
    - ImageIO==2.37.2
    - Jinja2==3.1.6
    - Markdown==3.10.1
    - MarkupSafe==2.1.5
    - PyYAML==6.0.3
    - Pygments==2.19.2
    - Send2Trash==2.1.0
    - accelerate==1.12.0
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.13.3
    - aiosignal==1.4.0
    - annotated-types==0.7.0
    - anyio==4.12.1
    - argon2-cffi==25.1.0
    - argon2-cffi-bindings==25.1.0
    - arrow==1.4.0
    - attrs==25.4.0
    - beautifulsoup4==4.14.3
    - bleach==6.3.0
    - bokeh==3.6.3
    - cachetools==7.0.0
    - certifi==2026.1.4
    - cffi==2.0.0
    - charset-normalizer==3.4.4
    - click==8.3.1
    - cloudpickle==3.1.2
    - colorcet==3.1.0
    - contourpy==1.3.3
    - cucim-cu13==25.12.0
    - cuda-bindings==13.0.3
    - cuda-core==0.3.2
    - cuda-pathfinder==1.3.4
    - cuda-python==13.0.3
    - cuda-toolkit==13.0.2
    - cudf-cu13==25.12.0
    - cupy-cuda13x==14.0.1
    - cycler==0.12.1
    - dask==2025.9.2
    - dask-cuda==25.12.0
    - dask-cudf-cu13==25.12.0
    - datashader==0.18.2
    - defusedxml==0.7.1
    - diffusers==0.36.0
    - distributed==2025.9.2
    - distributed-ucxx-cu13==0.47.0
    - donfig==0.8.1.post1
    - einops==0.8.2
    - einops-exts==0.0.4
    - fastjsonschema==2.21.2
    - fastrlock==0.8.3
    - filelock==3.20.0
    - fonttools==4.61.1
    - fqdn==1.5.1
    - frozenlist==1.8.0
    - fsspec==2025.12.0
    - geopandas==1.1.2
    - gitdb==4.0.12
    - google-crc32c==1.8.0
    - h11==0.16.0
    - hf-xet==1.2.0
    - holoviews==1.20.2
    - httpcore==1.0.9
    - httpx==0.28.1
    - huggingface_hub==1.3.2
    - idna==3.11
    - importlib_metadata==8.7.1
    - isoduration==20.11.0
    - joblib==1.5.3
    - jsonpointer==3.0.0
    - jsonschema==4.26.0
    - jsonschema-specifications==2025.9.1
    - jupyter-events==0.12.0
    - jupyter_client==8.8.0
    - jupyter_core==5.9.1
    - jupyter_server==2.17.0
    - jupyter_server_proxy==4.4.0
    - jupyter_server_terminals==0.5.4
    - jupyterlab_pygments==0.3.0
    - kiwisolver==1.4.9
    - lark==1.3.1
    - lazy_loader==0.4
    - libcudf-cu13==25.12.0
    - libcugraph-cu13==25.12.2
    - libcuml-cu13==25.12.0
    - libcuvs-cu13==25.12.0
    - libkvikio-cu13==25.12.0
    - libraft-cu13==25.12.0
    - librmm-cu13==25.12.0
    - libucx-cu13==1.19.0
    - libucxx-cu13==0.47.0
    - linkify-it-py==2.0.3
    - llvmlite==0.44.0
    - locket==1.0.0
    - markdown-it-py==4.0.0
    - matplotlib==3.10.8
    - mdit-py-plugins==0.5.0
    - mdurl==0.1.2
    - mistune==3.2.0
    - mpmath==1.3.0
    - msgpack==1.1.2
    - multidict==6.7.1
    - multipledispatch==1.0.0
    - nbclient==0.10.4
    - nbconvert==7.17.0
    - nbformat==5.10.4
    - networkx==3.6.1
    - numba==0.61.2
    - numba-cuda==0.19.2
    - numcodecs==0.16.5
    - numpy==2.2.6
    - nvidia-cublas==13.1.0.3
    - nvidia-cuda-cccl==13.1.115
    - nvidia-cuda-crt==13.1.115
    - nvidia-cuda-cupti==13.0.85
    - nvidia-cuda-nvcc==13.0.88
    - nvidia-cuda-nvrtc==13.0.88
    - nvidia-cuda-runtime==13.0.96
    - nvidia-cudnn-cu13==9.15.1.9
    - nvidia-cufft==12.0.0.61
    - nvidia-cufile==1.15.1.6
    - nvidia-curand==10.4.0.35
    - nvidia-cusolver==12.0.4.66
    - nvidia-cusparse==12.6.3.3
    - nvidia-cusparselt-cu13==0.8.0
    - nvidia-ml-py==13.590.48
    - nvidia-nccl-cu13==2.28.9
    - nvidia-nvimgcodec-cu13==0.6.1.37
    - nvidia-nvjitlink==13.0.88
    - nvidia-nvshmem-cu13==3.4.5
    - nvidia-nvtx==13.0.85
    - nvidia-nvvm==13.1.115
    - nvtx==0.2.14
    - pandas==2.3.3
    - pandocfilters==1.5.1
    - panel==1.7.5
    - param==2.3.1
    - partd==1.4.2
    - pillow==12.0.0
    - platformdirs==4.5.1
    - prometheus_client==0.24.1
    - propcache==0.4.1
    - protobuf==6.33.4
    - psutil==7.2.1
    - ptyprocess==0.7.0
    - pyarrow==23.0.0
    - pycparser==3.0
    - pyct==0.6.0
    - pydantic==2.12.5
    - pydantic_core==2.41.5
    - pylibcudf-cu13==25.12.0
    - pylibcugraph-cu13==25.12.2
    - pylibraft-cu13==25.12.0
    - pyogrio==0.12.1
    - pyparsing==3.3.2
    - pyproj==3.7.2
    - python-dateutil==2.9.0.post0
    - python-json-logger==4.0.0
    - pytz==2025.2
    - pyviz_comms==3.0.6
    - pyzmq==27.1.0
    - raft-dask-cu13==25.12.0
    - rapids-dask-dependency==25.12.1
    - rapids-logger==0.2.3
    - referencing==0.37.0
    - regex==2026.1.15
    - requests==2.32.5
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rfc3987-syntax==1.1.0
    - rich==14.3.2
    - rmm-cu13==25.12.0
    - rpds-py==0.30.0
    - safetensors==0.7.0
    - scikit-image==0.25.2
    - scikit-learn==1.8.0
    - scipy==1.17.0
    - sentry-sdk==2.50.0
    - setuptools==70.2.0
    - shapely==2.0.7
    - shellingham==1.5.4
    - simpervisor==1.0.0
    - six==1.17.0
    - smmap==5.0.2
    - sortedcontainers==2.4.0
    - soupsieve==2.8.3
    - sympy==1.14.0
    - tblib==3.2.2
    - terminado==0.18.1
    - threadpoolctl==3.6.0
    - tifffile==2026.1.28
    - timm==1.0.24
    - tinycss2==1.4.0
    - toolz==1.1.0
    - torch==2.10.0+cu130
    - torchvision==0.25.0+cu130
    - tornado==6.5.4
    - tqdm==4.67.1
    - traitlets==5.14.3
    - treelite==4.6.1
    - triton==3.6.0
    - typer-slim==0.21.1
    - typing-inspection==0.4.2
    - typing_extensions==4.15.0
    - tzdata==2025.3
    - uc-micro-py==1.0.3
    - ucxx-cu13==0.47.0
    - uri-template==1.3.0
    - urllib3==2.6.3
    - wandb==0.24.0
    - webcolors==25.10.0
    - webencodings==0.5.1
    - websocket-client==1.9.0
    - xarray==2026.1.0
    - xformers==0.0.34
    - xyzservices==2025.11.0
    - yarl==1.22.0
    - zarr==3.1.5
    - zict==3.0.0
    - zipp==3.23.0
